# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "adrernst" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: adrernst

# Build settings
markdown: kramdown
